services:
  - type: web
    name: analyse-financiere-backend
    env: python
    region: frankfurt  # ou oregon, singapore selon votre localisation
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false  # À configurer manuellement dans le dashboard Render
